"""Totals V1 feature foundation (Phase 3A + Phase 3B + Phase 3C + Phase 3D).

Phase 3A provides the deterministic data/chronology layer for the accepted
Totals V1 feature contract.

Phase 3B translates the accepted Phase 2 contract into row-level PBP
semantics, possession primitives, and per-game/per-team observation
construction.

Phase 3C extends the observation layer with the ten remaining selected
PBP primitive families (seconds/play, neutral seconds/play, neutral
pass rate, red-zone TD efficiency, goal-to-go TD efficiency,
sacks/dropback, air yards/attempt, YAC/completion, explosive pass rate,
explosive rush rate).

Phase 3D implements expanding entering-state aggregation with exact
metric-specific minima, offense/defense matchup combinations, rest/
roof/surface context features, Oracle QB entering-state v2 join, and
the exact 90-column Totals V1 feature table using Phase 3A block-start
freeze/commit mechanics.
"""

from .drive_observations import (
    CONTRACT_DRIVE_POINTS,
    CONTRACT_SCORING_RESULTS,
    DrivePointsError,
    GoalToGoOpportunity,
    PossessionObservation,
    RedZoneOpportunity,
    METRIC_GOAL_TO_GO_TD_RATE_DEFENSE_ALLOWED,
    METRIC_GOAL_TO_GO_TD_RATE_OFFENSE,
    METRIC_POINTS_PER_DRIVE,
    METRIC_RED_ZONE_TD_RATE_DEFENSE_ALLOWED,
    METRIC_RED_ZONE_TD_RATE_OFFENSE,
    METRIC_SCORING_DRIVE_RATE,
    METRIC_TURNOVERS_PER_DRIVE,
    build_possessions,
    drive_points_from_result,
    goal_to_go_opportunity_observations,
    is_scoring_result,
    points_per_drive_observation,
    possession_observations,
    red_zone_opportunity_observations,
    scoring_drive_observation,
    turnovers_per_drive_observation,
)
from .game_observations import (
    GameObservationError,
    METRIC_AIR_YARDS_PER_ATTEMPT_DEFENSE_ALLOWED,
    METRIC_AIR_YARDS_PER_ATTEMPT_OFFENSE,
    METRIC_COMPLETIONS_DEFENSE_ALLOWED,
    METRIC_COMPLETIONS_OFFENSE,
    METRIC_DROPBACKS_DEFENSE_ALLOWED,
    METRIC_DROPBACKS_OFFENSE,
    METRIC_EPA_PLAY_DEFENSE_ALLOWED,
    METRIC_EPA_PLAY_OFFENSE,
    METRIC_EXPLOSIVE_PASS_RATE_DEFENSE_ALLOWED,
    METRIC_EXPLOSIVE_PASS_RATE_OFFENSE,
    METRIC_EXPLOSIVE_RUSH_RATE_DEFENSE_ALLOWED,
    METRIC_EXPLOSIVE_RUSH_RATE_OFFENSE,
    METRIC_GOAL_TO_GO_TD_RATE_DEFENSE_ALLOWED,
    METRIC_GOAL_TO_GO_TD_RATE_OFFENSE,
    METRIC_NEUTRAL_PASS_RATE_DEFENSE_ALLOWED,
    METRIC_NEUTRAL_PASS_RATE_OFFENSE,
    METRIC_PASS_ATTEMPTS_DEFENSE_ALLOWED,
    METRIC_PASS_ATTEMPTS_OFFENSE,
    METRIC_POINTS_PER_DRIVE_DEFENSE_ALLOWED,
    METRIC_POINTS_PER_DRIVE_OFFENSE,
    METRIC_RED_ZONE_TD_RATE_DEFENSE_ALLOWED,
    METRIC_RED_ZONE_TD_RATE_OFFENSE,
    METRIC_RUSH_ATTEMPTS_DEFENSE_ALLOWED,
    METRIC_RUSH_ATTEMPTS_OFFENSE,
    METRIC_SACKS_DEFENSE_ALLOWED,
    METRIC_SACKS_OFFENSE,
    METRIC_SACKS_PER_DROPBACK_DEFENSE_ALLOWED,
    METRIC_SACKS_PER_DROPBACK_OFFENSE,
    METRIC_SCORING_DRIVE_RATE_DEFENSE_ALLOWED,
    METRIC_SCORING_DRIVE_RATE_OFFENSE,
    METRIC_SUCCESS_DEFENSE_ALLOWED,
    METRIC_SUCCESS_OFFENSE,
    METRIC_TURNOVERS_DEFENSE_ALLOWED,
    METRIC_TURNOVERS_OFFENSE,
    METRIC_TURNOVERS_PER_DRIVE_DEFENSE_ALLOWED,
    METRIC_TURNOVERS_PER_DRIVE_OFFENSE,
    METRIC_YAC_PER_COMPLETION_DEFENSE_ALLOWED,
    METRIC_YAC_PER_COMPLETION_OFFENSE,
    aggregate_possession_metrics,
    aggregate_row_metrics,
    build_game_observations,
    build_game_observations_with_provenance,
    build_team_updates,
)
from .pace_observations import (
    MAX_INTERVAL_SECONDS,
    METRIC_NEUTRAL_SECONDS_PLAY_DEFENSE_ALLOWED,
    METRIC_NEUTRAL_SECONDS_PLAY_OFFENSE,
    METRIC_SECONDS_PLAY_DEFENSE_ALLOWED,
    METRIC_SECONDS_PLAY_OFFENSE,
    PaceInterval,
    PaceIntervalError,
    build_pace_intervals,
    game_half_for_qtr,
    pace_interval_observations,
)
from .pbp_semantics import (
    FIRST_HALF_QTRS,
    NEUTRAL_QTRS,
    OVERTIME_QTR,
    PbpSemanticsError,
    REQUIRED_PBP_COLUMNS,
    SECOND_HALF_QTRS,
    VFP_PLAY_TYPES,
    air_yards_observed_expr,
    air_yards_observation,
    annotate_pbp_semantics,
    completion_expr,
    completion_observation,
    dropback_expr,
    dropback_fallback_expr,
    dropback_fallback_observation,
    dropback_observation,
    epa_observation,
    epa_observed_expr,
    explosive_pass_event_expr,
    explosive_pass_observation,
    explosive_rush_event_expr,
    explosive_rush_observation,
    goal_to_go_opportunity_membership_expr,
    interception_event_expr,
    lost_fumble_event_expr,
    neutral_expr,
    neutral_pass_attempt_observation,
    neutral_rush_attempt_observation,
    pass_attempt_expr,
    pass_attempt_observation,
    red_zone_opportunity_membership_expr,
    rush_attempt_expr,
    rush_attempt_observation,
    sack_observation,
    sack_within_dropback_observation,
    success_observation,
    success_observed_expr,
    turnover_event_expr,
    turnover_event_observation,
    vfp_expr,
    yac_observed_expr,
    yac_observation,
    yards_gained_observed_expr,
)

# Phase 3D: entering-state aggregation, matchup, context, feature table.
from .context_features import extract_context_features
from .entering_state import (
    MATCHUP_FAMILIES,
    MetricFamilyConfig,
    compute_matchup_pair,
    extract_entering_rate,
)
from .feature_table import (
    EXACT_90_COLUMNS,
    FeatureTableError,
    TotalsV1FeatureTable,
    build_totals_v1_feature_table,
)

__all__ = [
    # pbp_semantics — predicates
    "FIRST_HALF_QTRS",
    "NEUTRAL_QTRS",
    "OVERTIME_QTR",
    "PbpSemanticsError",
    "REQUIRED_PBP_COLUMNS",
    "SECOND_HALF_QTRS",
    "VFP_PLAY_TYPES",
    "air_yards_observed_expr",
    "annotate_pbp_semantics",
    "completion_expr",
    "dropback_expr",
    "dropback_fallback_expr",
    "epa_observed_expr",
    "explosive_pass_event_expr",
    "explosive_rush_event_expr",
    "goal_to_go_opportunity_membership_expr",
    "interception_event_expr",
    "lost_fumble_event_expr",
    "neutral_expr",
    "pass_attempt_expr",
    "red_zone_opportunity_membership_expr",
    "rush_attempt_expr",
    "success_observed_expr",
    "turnover_event_expr",
    "vfp_expr",
    "yac_observed_expr",
    "yards_gained_observed_expr",
    # pbp_semantics — per-row observation extractors
    "air_yards_observation",
    "completion_observation",
    "dropback_fallback_observation",
    "dropback_observation",
    "epa_observation",
    "explosive_pass_observation",
    "explosive_rush_observation",
    "neutral_pass_attempt_observation",
    "neutral_rush_attempt_observation",
    "pass_attempt_observation",
    "rush_attempt_observation",
    "sack_observation",
    "sack_within_dropback_observation",
    "success_observation",
    "turnover_event_observation",
    "yac_observation",
    # pace_observations
    "MAX_INTERVAL_SECONDS",
    "METRIC_NEUTRAL_SECONDS_PLAY_DEFENSE_ALLOWED",
    "METRIC_NEUTRAL_SECONDS_PLAY_OFFENSE",
    "METRIC_SECONDS_PLAY_DEFENSE_ALLOWED",
    "METRIC_SECONDS_PLAY_OFFENSE",
    "PaceInterval",
    "PaceIntervalError",
    "build_pace_intervals",
    "game_half_for_qtr",
    "pace_interval_observations",
    # drive_observations
    "CONTRACT_DRIVE_POINTS",
    "CONTRACT_SCORING_RESULTS",
    "DrivePointsError",
    "GoalToGoOpportunity",
    "PossessionObservation",
    "RedZoneOpportunity",
    "METRIC_GOAL_TO_GO_TD_RATE_DEFENSE_ALLOWED",
    "METRIC_GOAL_TO_GO_TD_RATE_OFFENSE",
    "METRIC_POINTS_PER_DRIVE",
    "METRIC_RED_ZONE_TD_RATE_DEFENSE_ALLOWED",
    "METRIC_RED_ZONE_TD_RATE_OFFENSE",
    "METRIC_SCORING_DRIVE_RATE",
    "METRIC_TURNOVERS_PER_DRIVE",
    "build_possessions",
    "drive_points_from_result",
    "goal_to_go_opportunity_observations",
    "is_scoring_result",
    "points_per_drive_observation",
    "possession_observations",
    "red_zone_opportunity_observations",
    "scoring_drive_observation",
    "turnovers_per_drive_observation",
    # game_observations
    "GameObservationError",
    "METRIC_AIR_YARDS_PER_ATTEMPT_DEFENSE_ALLOWED",
    "METRIC_AIR_YARDS_PER_ATTEMPT_OFFENSE",
    "METRIC_COMPLETIONS_DEFENSE_ALLOWED",
    "METRIC_COMPLETIONS_OFFENSE",
    "METRIC_DROPBACKS_DEFENSE_ALLOWED",
    "METRIC_DROPBACKS_OFFENSE",
    "METRIC_EPA_PLAY_DEFENSE_ALLOWED",
    "METRIC_EPA_PLAY_OFFENSE",
    "METRIC_EXPLOSIVE_PASS_RATE_DEFENSE_ALLOWED",
    "METRIC_EXPLOSIVE_PASS_RATE_OFFENSE",
    "METRIC_EXPLOSIVE_RUSH_RATE_DEFENSE_ALLOWED",
    "METRIC_EXPLOSIVE_RUSH_RATE_OFFENSE",
    "METRIC_NEUTRAL_PASS_RATE_DEFENSE_ALLOWED",
    "METRIC_NEUTRAL_PASS_RATE_OFFENSE",
    "METRIC_PASS_ATTEMPTS_DEFENSE_ALLOWED",
    "METRIC_PASS_ATTEMPTS_OFFENSE",
    "METRIC_RUSH_ATTEMPTS_DEFENSE_ALLOWED",
    "METRIC_RUSH_ATTEMPTS_OFFENSE",
    "METRIC_SACKS_DEFENSE_ALLOWED",
    "METRIC_SACKS_OFFENSE",
    "METRIC_SACKS_PER_DROPBACK_DEFENSE_ALLOWED",
    "METRIC_SACKS_PER_DROPBACK_OFFENSE",
    "METRIC_SUCCESS_DEFENSE_ALLOWED",
    "METRIC_SUCCESS_OFFENSE",
    "METRIC_TURNOVERS_DEFENSE_ALLOWED",
    "METRIC_TURNOVERS_OFFENSE",
    "METRIC_YAC_PER_COMPLETION_DEFENSE_ALLOWED",
    "METRIC_YAC_PER_COMPLETION_OFFENSE",
    "aggregate_possession_metrics",
    "aggregate_row_metrics",
    "build_game_observations",
    "build_game_observations_with_provenance",
    "build_team_updates",
    # Phase 3D — entering-state, matchup, context, feature table
    "EXACT_90_COLUMNS",
    "FeatureTableError",
    "MATCHUP_FAMILIES",
    "MetricFamilyConfig",
    "TotalsV1FeatureTable",
    "build_totals_v1_feature_table",
    "compute_matchup_pair",
    "extract_context_features",
    "extract_entering_rate",
]
