from __future__ import annotations
import json,re,struct
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; FRONTEND=ROOT/'frontend'
def png_size(p):
 d=p.read_bytes(); assert d[:8]==b'\x89PNG\r\n\x1a\n'; return struct.unpack('>II',d[16:24])
def test_manifest_and_install_assets_are_valid():
 m=json.loads((FRONTEND/'manifest.webmanifest').read_text()); assert m['name']==m['short_name']=='NFL EDGE'; assert m['display']=='standalone'; assert m['background_color']=='#070a0f'; icons={x['sizes']:x for x in m['icons']}; assert {'192x192','512x512'}<=set(icons); assert 'maskable' in icons['192x192']['purpose']; assert png_size(FRONTEND/icons['192x192']['src'].removeprefix('./'))==(192,192); assert png_size(FRONTEND/icons['512x512']['src'].removeprefix('./'))==(512,512)
def test_index_mobile_accessible_model_driven():
 h=(FRONTEND/'index.html').read_text(); assert 'width=device-width' in h and 'manifest.webmanifest' in h and 'data/latest.json' not in h; assert 'id="offer-book"' not in h; assert 'available at any sportsbook' in h; assert 'class="skip-link"' in h and 'aria-live=' in h; assert 'backend' not in h.lower(); assert 'nfl-edge-wordmark.png' in h and h.count('class="tab-icon"')==4; assert 'ui-motion.css' in h and 'ui-theme-finish.css' in h
def test_service_worker_never_caches_api_responses():
 s=(FRONTEND/'sw.js').read_text(); assert "url.pathname.startsWith('/api/')" in s; assert "fetch(request,{cache:'no-store'})" in s; assert "nfl-edge-shell-v13" in s; assert "./ui-polish.css" in s and "./ui-branding.css" in s and "./ui-motion.css" in s and "./ui-theme-finish.css" in s; assert "./assets/nfl-edge-wordmark.png" in s; shell=re.search(r'APP_SHELL=\[(.*?)\];',s,re.S).group(1); assert '/api/' not in shell
def test_no_mock_or_frozen_business_logic():
 js='\n'.join(p.read_text() for p in FRONTEND.glob('*.js')); forbidden=['data/latest.json','PER_WAGER_CAP','SLATE_CAP','STAKE_FLOOR','UNIT_LADDER','RELIABILITY_HAIRCUT','PT_CONCESSION_PP','MANUAL_DEFAULT_PROB','americanToImplied','stakeFromUnits','unitDollars','ODDS_API_KEY','api.the-odds-api.com']; [(_ for _ in ()).throw(AssertionError(x)) for x in forbidden if x in js]
def test_api_routes_centralized_relative():
 a=(FRONTEND/'api.js').read_text(); app=(FRONTEND/'app.js').read_text(); core=(FRONTEND/'ui-core.js').read_text(); required=['/api/v1/health','/api/v1/auth/register','/api/v1/auth/login','/api/v1/auth/logout','/api/v1/auth/me','/api/v1/profile','/api/v1/product/latest','/api/v1/games','/api/v1/evaluate-offer','/api/v1/wagers']; assert all(x in a for x in required); assert "credentials:'include'" in a and "cache:'no-store'" in a; assert 'http://' not in a and 'https://' not in a; assert '/api/v1/' not in app and '/api/v1/' not in core
def test_user_facing_app_copy_avoids_backend_jargon():
 app=(FRONTEND/'app.js').read_text(); assert 'Backend unavailable' not in app; assert 'Backend details' not in app; assert 'backend-calculated' not in app; assert 'backend session' not in app; assert 'Model details' in app; assert 'model-calculated' in app
def test_detail_market_rows_are_actionable_and_legible():
 app=(FRONTEND/'app.js').read_text(); css=(FRONTEND/'styles.css').read_text(); polish=(FRONTEND/'ui-polish.css').read_text(); assert 'data-detail-offer' in app and 'evaluateDetailOffer' in app and 'openDetailExact' in app; assert '.detail-offer' in css and '.market-offers' in css and '.model-value' in css; assert '.detail-market-tabs' in polish and '.evaluation-grid' in polish
def test_app_grade_hierarchy_and_extreme_black_structure():
 p=(FRONTEND/'ui-polish.css').read_text(); assert 'App-grade hierarchy pass' in p; assert '.gmatch{display:grid;grid-template-columns:minmax(0,1fr)' in p; assert '#view-detail .detail-card{padding:0;border:0;background:transparent' in p; assert '.model-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))' in p; assert '[data-theme="extreme"]{--bg:#000;--surface:#000;--surface-2:#000' in p
def test_branding_nav_and_ultra_warning_are_presentation_only():
 h=(FRONTEND/'index.html').read_text(); b=(FRONTEND/'ui-branding.css').read_text(); u=(FRONTEND/'ux.js').read_text(); finish=(FRONTEND/'ui-theme-finish.css').read_text(); assert 'class="app-logo"' in h and 'ui-branding.css' in h; assert '.tab .tab-icon' in b and 'font-size:1.42rem' in b; assert 'content:url("data:image/png;base64,' in b; assert '[data-theme="extreme"] .app-logo' in finish and '[data-theme="fancy"] .app-logo' in finish; assert 'Ultra staking' in u and 'does not increase win probability' in u and 'expected percentage return' in u and 'Only the dollar swings get larger' in u; assert 'data-ultra-confirm' in u and 'data-ultra-back' in u
def test_motion_setting_and_branded_launch_are_local_presentation_only():
 u=(FRONTEND/'ux.js').read_text(); b=(FRONTEND/'ui-branding.css').read_text(); m=(FRONTEND/'ui-motion.css').read_text(); finish=(FRONTEND/'ui-theme-finish.css').read_text(); assert 'nfl-edge-motion-v1' in u; assert 'Transitions & loading animation' in u; assert 'prefers-reduced-motion: reduce' in u; assert 'armTabTransition' in u and 'view-transition-finish' in u; assert 'app-ready' in u; assert 'Loading the board' in b; assert '.motion-switch' in b; assert 'body::after' in m and '@keyframes yard-lines-move' in m; assert 'body::before{animation:none!important' in m; assert '@media(prefers-reduced-motion:reduce)' in m; assert 'view-enter-finish' in finish and '#2f8a45' in finish and '20   25   30' in finish
def test_wager_dialog_is_theme_safe_and_mobile_bounded():
 finish=(FRONTEND/'ui-theme-finish.css').read_text(); assert '.wager-dialog{color:var(--ink)' in finish; assert 'grid-template-columns:minmax(0,1fr) minmax(0,1fr)' in finish; assert '.wager-dialog .manual-field input{display:block;width:100%;min-width:0' in finish
def test_local_storage_is_presentation_only():
 app=(FRONTEND/'app.js').read_text(); keys=re.findall(r"localStorage\.(?:getItem|setItem)\((?:key|'([^']+)'|\"([^\"]+)\")",app); text=' '.join(sum(([a,b] for a,b in keys),[])); assert 'bankroll' not in text.lower() and 'wager' not in text.lower() and 'password' not in text.lower()
def test_mobile_touch_and_states_exist():
 c=(FRONTEND/'styles.css').read_text(); p=(FRONTEND/'ui-polish.css').read_text(); assert '@media(max-width:340px)' in c and 'min-height:44px' in c and ':focus-visible' in c and '.state-chip' in c and '.roof-badge' in c; assert '@media(max-width:320px)' in p
