import {ApiClient,ApiError} from './api.js';
import {RISK_PROFILES,WAGER_STATUSES,esc,odds,line,money,pct,units,healthPresentation,playThroughPresentation,roofPresentation,headlinePresentation,buildHeadlineWagerPayload,buildExactWagerPayload} from './ui-core.js';
import {compareOffer,comparisonLabel,findPinnyOffer} from './market-compare.js';

const api=new ApiClient({baseUrl:globalThis.NFL_EDGE_API_BASE||''}),$=id=>document.getElementById(id);
const state={user:null,profile:null,health:null,view:null,games:[],wagers:[],exact:null,detailGame:null,detailOffer:null,pending:null,refreshError:null,install:null};
const SETTLED=new Set(['WON','LOST','PUSH','VOID','CANCELLED']);
const safe=(e,c='')=>{if(!(e instanceof ApiError))return'Something went wrong.';if(e.status===0)return'App unavailable. Check your connection.';if(c==='login'&&e.status===401)return'Invalid username or password.';if(e.status===401)return'Session expired — sign in again.';if(c==='wager'&&e.status===409)return'Current offer is no longer valid; refresh and review the updated board.';if(c==='exact'&&e.status===422)return'Unsupported exact offer.';if(e.status===503)return'Recommendations temporarily unavailable.';return'Request could not be completed.'};
function toast(m){$('toast').textContent=m;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').hidden=true,3200)}
const product=()=>state.view?.product||null,overlays=()=>state.view?.headline_overlays||{},auth=()=>!!state.user;
function renderHealth(){const h=healthPresentation(state.health);$('health-label').textContent=h.label;const b=$('status-banner'),offline=!navigator.onLine;b.hidden=!offline&&h.key==='fresh'&&!state.refreshError;if(!b.hidden)b.textContent=offline?'Offline — live recommendations and account state are unavailable.':state.refreshError||h.label}
function renderUser(){const h=$('user-strip');h.innerHTML=state.user?`<div><strong>${esc(state.user.username)}</strong><span>${money(state.user.bankroll)} · ${esc(state.user.risk_profile)}</span></div><button class="text-btn" type="button" data-account>Settings</button>`:`<div><strong>Live board</strong><span>Units are public. Sign in for model-calculated dollar stakes and saved wagers.</span></div><button class="text-btn" type="button" data-account>Sign in</button>`;h.querySelector('[data-account]').onclick=()=>show('account')}
const target=(x,label)=>x?`${label}${x.line==null?'':` ${line(x.line)}`} ${odds(x.price_american)}`:'';
function headlineCard(k,h){const o=overlays()[k]||{},p=headlinePresentation(h,o,auth()),pt=playThroughPresentation(h.line,h.american_odds,h.play_through);const title=h.matchup?`${h.matchup.away_team} @ ${h.matchup.home_team} — ${h.selection||''} ${line(h.line)} · ${odds(h.american_odds)} · ${h.book||''}`:(h.lane||k);const stateText={BET:'BET',TARGET_ONLY:'WATCH PRICE',NO_PLAY:'NO PLAY',SUPPRESSED:'SUPPRESSED',UNSUPPORTED:'UNSUPPORTED'}[p.state]||p.state;return `<article class="hcard state-${p.state.toLowerCase()}" data-lane="${h.lane==='HIT_RATE'?'HHR':h.lane}"><div class="hcard-row"><span class="hcard-tag">${esc(h.lane==='HIT_RATE'?'Hit Rate':h.lane)}</span><span class="state-chip">${esc(p.state.replaceAll('_',' '))}</span></div><div class="hcard-title">${esc(title)}</div><div class="hcard-action"><span class="action-verb ${p.state==='BET'&&!p.duplicate?'':'is-no'}">${stateText}</span><span class="action-stake"><span class="units">${units(h.recommended_units)}</span>${p.recommendedDollars!=null?money(p.recommendedDollars):p.showSignIn?'<span class="muted">Sign in for $ stake</span>':''}</span></div>${p.duplicate?`<div class="suppression-note">Duplicate exact offer — stake already covered by ${o.duplicate_of_lane?esc(o.duplicate_of_lane):'another model recommendation'}.</div>`:''}${p.logged?`<div class="logged-note">Wager Logged${o.actual_dollars!=null?` · ${money(o.actual_dollars)}`:''}${o.wager_status?` · ${esc(o.wager_status)}`:''}</div>`:''}${pt?`<div class="hcard-secondary"><span class="verb">Play Through</span> ${target(pt,'')}${pt.inside===true?' · current offer inside range':pt.inside===false?' · outside range':''}</div>`:''}${h.value_at?`<div class="hcard-secondary value-at"><span class="verb">Value At</span> ${target(h.value_at,'')}${p.state==='TARGET_ONLY'?' · watch price, not a current bet':''}</div>`:''}${(h.warnings||[]).length?`<ul class="warning-list">${h.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul>`:''}<details class="hcard-math"><summary>Model details</summary><div class="hcard-math-body"><span class="k">model probability</span><span class="v">${pct(h.model_probability)}</span><span class="k">trust probability</span><span class="v">${pct(h.trust_probability)}</span><span class="k">market probability</span><span class="v">${pct(h.market_probability)}</span><span class="k">EV</span><span class="v">${h.ev==null?'—':`${(Number(h.ev)*100).toFixed(2)}%`}</span><span class="k">reliability</span><span class="v">${esc(h.reliability||'—')}</span></div></details>${p.actionable?`<button class="btn-primary card-action" type="button" data-log="${k}">Log Wager</button>`:p.showSignIn?'<button class="btn-secondary card-action" type="button" data-signin>Sign in to personalize</button>':''}</article>`}
function renderBoard(){const h=$('headlines'),p=product();if(!p){h.innerHTML=`<div class="empty-state"><strong>Recommendations temporarily unavailable</strong><span>${esc(state.refreshError||'No current recommendations are available.')}</span></div>`;return}h.innerHTML=['hit_rate','balanced','value'].map(k=>headlineCard(k,p.headlines[k])).join('');h.querySelectorAll('[data-log]').forEach(b=>b.onclick=()=>openHeadline(b.dataset.log));h.querySelectorAll('[data-signin]').forEach(b=>b.onclick=()=>show('account'));$('product-version').textContent=`Product ${p.product_version}`}
function gameRoof(g){const r=roofPresentation(g);return r.label?`<span class="roof-badge roof-${r.kind}">${esc(r.label)}</span>`:''}
function renderGames(){const h=$('games-list');if(!state.games.length){h.innerHTML='<div class="empty-state">No games available.</div>';return}h.innerHTML=state.games.map(g=>`<button class="gcard" type="button" data-game="${esc(g.game_id)}"><span class="gmatch"><span>${esc(g.away_team)} @ ${esc(g.home_team)}</span><span class="gtime">${esc(new Date(g.kickoff_at_utc).toLocaleString())}</span></span><span class="gmeta">${esc(g.quarterbacks?.away?.expected_starter||'QB pending')} vs ${esc(g.quarterbacks?.home?.expected_starter||'QB pending')} · ${esc(g.game_status)}</span><span class="game-badges">${gameRoof(g)}${g.warnings?.length?`<span class="warning-dot">${g.warnings.length} warning${g.warnings.length===1?'':'s'}</span>`:''}</span></button>`).join('');h.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game))}
function modelValue(name,value){if(value==null)return'—';const n=Number(value);if(!Number.isFinite(n))return'—';if(name==='QB Elo'||name==='XGBoost V2')return pct(n);if(name==='Expected Margin')return`${n>0?'+':''}${n.toFixed(1)} pts`;if(name==='Ridge Totals R4')return`${n.toFixed(1)} pts`;return n.toFixed(3)}
function modelRow(n,o={}){return `<div class="model-row"><span class="model-name"><strong>${esc(n)}</strong><small>${esc(o.status||'UNAVAILABLE')} · ${esc(o.support||'—')}</small></span><span class="model-value">${modelValue(n,o.prediction)}</span></div>`}
const bookName=book=>book==='DRAFTKINGS'?'DraftKings':book==='FANDUEL'?'FanDuel':'Pinnacle';
const marketName=market=>market==='moneyline'?'Moneyline':market==='spread'?'Spread':'Total';
function detailOfferMarkup(g,market,book,o){const pinny=findPinnyOffer(g.market_board?.[market]?.PINNACLE||[],o),status=compareOffer(market,o,pinny),cmp=status?` cmp-${status}`:'',label=status?comparisonLabel(status):'';return `<button class="detail-offer${cmp}" type="button" data-detail-offer data-market="${market.toUpperCase()}" data-book="${book}" data-selection="${esc(o.selection)}" data-line="${o.line==null?'':esc(o.line)}" data-price="${esc(o.price)}"><span class="detail-offer-selection"><strong>${esc(o.selection)}${o.line==null?'':` ${line(o.line)}`}</strong><small>${esc(o.freshness?.state||'')}</small></span><span class="detail-offer-price">${odds(o.price)}</span>${label?`<span class="detail-offer-compare">${esc(label)}</span>`:''}<span class="detail-offer-cta">Check offer ›</span></button>`}
function benchmarkOfferMarkup(o){return `<div class="detail-offer benchmark-offer"><span class="detail-offer-selection"><strong>${esc(o.selection)}${o.line==null?'':` ${line(o.line)}`}</strong><small>${esc(o.freshness?.state||'')}</small></span><span class="detail-offer-price">${odds(o.price)}</span><span class="detail-offer-compare">benchmark</span></div>`}
function marketSection(g,market){return `<section class="market-section"><div class="market-section-head"><h3>${marketName(market)}</h3><span>Tap DK or FD to evaluate</span></div>${['DRAFTKINGS','FANDUEL','PINNACLE'].map(book=>{const offers=g.market_board?.[market]?.[book]||[];if(!offers.length)return'';const retail=book!=='PINNACLE';return `<div class="market-book ${retail?'':'benchmark-book'}"><div class="market-book-name">${bookName(book)}${retail?'':' · benchmark only'}</div><div class="market-offers">${offers.map(o=>retail?detailOfferMarkup(g,market,book,o):benchmarkOfferMarkup(o)).join('')}</div></div>`}).join('')}</section>`}
async function openGame(id){show('detail');state.detailOffer=null;$('detail-card').innerHTML='<div class="loading-card">Loading game…</div>';try{const g=(await api.game(id)).game,r=roofPresentation(g),x=g.football_outputs?.xgboost_v2||{};state.detailGame=g;const roof=r.label?`<section class="roof-panel roof-${r.kind}"><h3>${esc(r.label)}</h3><p>${esc(r.detail||'')}</p>${x.xgboost_open_probability!=null?`<div class="roof-scenarios"><div>OPEN <strong>${pct(x.xgboost_open_probability)}</strong></div><div>CLOSED <strong>${pct(x.xgboost_closed_probability)}</strong></div></div>`:''}</section>`:'';const q=['away','home'].map(s=>{const q=g.quarterbacks?.[s]||{};return `<div class="qb-card"><span>${s.toUpperCase()} · ${esc(q.team||'')}</span><strong>${esc(q.expected_starter||'Starter unavailable')}</strong><small>${esc(q.resolution_status||'')} · ${esc(q.freshness?.state||'')}</small></div>`}).join('');const markets=['moneyline','spread','total'].map(m=>marketSection(g,m)).join('');$('detail-card').innerHTML=`<button class="text-btn" type="button" data-back>← Board</button><h2>${esc(g.away_team)} @ ${esc(g.home_team)}</h2><p class="muted">${esc(g.game_status)} · ${esc(g.venue||'')}</p>${roof}<h3>Expected quarterbacks</h3><div class="qb-grid">${q}</div><h3>Football outputs</h3><div class="model-grid">${modelRow('QB Elo',g.football_outputs?.qb_elo)}${modelRow('XGBoost V2',x)}${modelRow('Expected Margin',g.football_outputs?.expected_margin)}${modelRow('Ridge Totals R4',g.football_outputs?.ridge_totals_r4)}</div><div class="detail-market-heading"><h3>Sportsbook offers</h3><p>Tap any DraftKings or FanDuel offer to see the model recommendation for that exact line and price.</p></div><div id="detail-offer-result" class="detail-offer-result" aria-live="polite"></div>${markets}`;$('detail-card').querySelector('[data-back]').onclick=()=>show('board');$('detail-card').querySelectorAll('[data-detail-offer]').forEach(b=>b.onclick=()=>evaluateDetailOffer(b))}catch(e){$('detail-card').innerHTML=`<div class="empty-state">${esc(safe(e))}</div>`}}
function exactSelections(){const g=state.games.find(x=>String(x.game_id)===$('offer-game').value),m=$('offer-market').value;if(!g)return;$('offer-selection').innerHTML=(m==='TOTAL'?['OVER','UNDER']:[g.away_team,g.home_team]).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('offer-line').disabled=m==='MONEYLINE';if(m==='MONEYLINE')$('offer-line').value=''}
function populateExact(){const s=$('offer-game'),old=s.value;s.innerHTML=state.games.map(g=>`<option value="${esc(g.game_id)}">${esc(g.away_team)} @ ${esc(g.home_team)}</option>`).join('');if(state.games.some(g=>String(g.game_id)===old))s.value=old;exactSelections()}
const sameLine=(a,b)=>(a==null&&b==null)||(a!=null&&b!=null&&Number(a)===Number(b));
function findExactWager(offer){return state.wagers.find(w=>w.source_type==='EXACT_OFFER'&&String(w.game_id)===String(offer.game_id)&&String(w.market_type)===String(offer.market_type)&&String(w.selection)===String(offer.selection)&&String(w.book)===String(offer.book)&&sameLine(w.line,offer.line)&&Number(w.price)===Number(offer.price))||null}
function evaluationMarkup(x,context){const {response,offer}=x,v=response.evaluation,pt=playThroughPresentation(offer.line,offer.price,v.play_through),logged=x.logged||findExactWager(offer);x.logged=logged;const action=v.verdict==='BET'?(logged?`<div class="logged-note">Wager Logged${logged.actual_dollars!=null?` · ${money(logged.actual_dollars)}`:''}${logged.status?` · ${esc(logged.status)}`:''}</div>`:auth()?`<button class="btn-primary" type="button" data-log-${context}>Log wager</button>`:'<button class="btn-secondary" type="button" data-signin>Sign in to personalize & log</button>'):'';return `<section class="detail-verdict offer-evaluation"><div class="offer-evaluation-head"><span class="state-chip">${esc(v.verdict)}</span><span class="offer-source">${offer.book==='MANUAL'?'Manual offer':bookName(offer.book)}</span></div><h3>${esc(offer.selection)} ${line(offer.line)} · ${odds(offer.price)}</h3><div class="hcard-action"><span class="action-verb ${v.verdict==='BET'?'':'is-no'}">${v.verdict==='TARGET_ONLY'?'WATCH PRICE':esc(v.verdict)}</span><span>${units(v.recommended_units)} ${response.recommended_dollars!=null?money(response.recommended_dollars):''}</span></div>${pt?`<div class="hcard-secondary"><span class="verb">Play Through</span> ${target(pt,'')}</div>`:''}${v.value_at?`<div class="hcard-secondary value-at"><span class="verb">Value At</span> ${target(v.value_at,'')} · watch price</div>`:''}<p>Model ${pct(v.probability)} · Trust ${pct(v.trust_probability)} · EV ${v.ev==null?'—':`${(Number(v.ev)*100).toFixed(2)}%`}</p>${action}</section>`}
function renderExactResult(){const x=state.exact;if(!x)return;$('exact-result').innerHTML=evaluationMarkup(x,'exact');$('exact-result').querySelector('[data-log-exact]')?.addEventListener('click',openExact);$('exact-result').querySelector('[data-signin]')?.addEventListener('click',()=>show('account'))}
function renderDetailOfferResult(){const h=$('detail-offer-result'),x=state.detailOffer;if(!h||!x)return;h.innerHTML=evaluationMarkup(x,'detail');h.querySelector('[data-log-detail]')?.addEventListener('click',openDetailExact);h.querySelector('[data-signin]')?.addEventListener('click',()=>show('account'))}
async function evaluateDetailOffer(button){if(!state.detailGame)return;const rawLine=button.dataset.line,offer={game_id:String(state.detailGame.game_id),market_type:button.dataset.market,selection:button.dataset.selection,book:button.dataset.book,line:rawLine===''?null:Number(rawLine),price:Number(button.dataset.price)},h=$('detail-offer-result');h.innerHTML='<div class="loading-card">Checking this offer…</div>';try{const response=await api.evaluateOffer(offer);state.detailOffer={response,offer,logged:findExactWager(offer)};renderDetailOfferResult();h.scrollIntoView({behavior:'smooth',block:'nearest'})}catch(err){h.innerHTML=`<div class="empty-state">${esc(safe(err,'exact'))}</div>`}}
async function evaluateExact(e){e.preventDefault();const market=$('offer-market').value,lt=$('offer-line').value.trim(),offer={game_id:$('offer-game').value,market_type:market,selection:$('offer-selection').value,book:'MANUAL',line:market==='MONEYLINE'?null:Number(lt),price:Number($('offer-price').value)};if(!Number.isFinite(offer.price)||(market!=='MONEYLINE'&&(!lt||!Number.isFinite(offer.line)))){$('exact-error').textContent='Enter a valid offer.';return}try{const response=await api.evaluateOffer(offer);state.exact={response,offer,logged:findExactWager(offer)};renderExactResult();$('exact-error').textContent=''}catch(err){$('exact-error').textContent=safe(err,'exact')}}
const idem=p=>`${p}-${globalThis.crypto?.randomUUID?.()||Date.now()}`.slice(0,128);
function dialog(title,copy,u,d,pending){state.pending={...pending,idempotencyKey:idem(pending.kind.toLowerCase())};$('wager-dialog-title').textContent=title;$('wager-dialog-copy').textContent=copy;$('wager-units').value=u??'';$('wager-dollars').value=d??'';$('wager-note').value='';$('wager-error').textContent='';$('wager-dialog').showModal()}
function openHeadline(k){if(!auth())return show('account');const h=product().headlines[k],o=overlays()[k]||{},p=headlinePresentation(h,o,true);if(!p.actionable)return;dialog(`Log ${h.lane} wager`,`${h.selection} ${line(h.line)} · ${odds(h.american_odds)} · ${h.book}`,h.recommended_units,o.recommended_dollars,{kind:'HEADLINE',headline:h,productVersion:product().product_version})}
function openExact(){if(!auth())return show('account');const x=state.exact;if(!x||x.response.evaluation.verdict!=='BET'||x.logged)return;dialog('Log exact-offer wager',`${x.offer.selection} ${line(x.offer.line)} · ${odds(x.offer.price)}`,x.response.evaluation.recommended_units,x.response.recommended_dollars,{kind:'EXACT_OFFER',origin:'CHECK',offer:x.offer,productVersion:x.response.product_version})}
function openDetailExact(){if(!auth())return show('account');const x=state.detailOffer;if(!x||x.response.evaluation.verdict!=='BET'||x.logged)return;dialog('Log sportsbook wager',`${bookName(x.offer.book)} · ${x.offer.selection} ${line(x.offer.line)} · ${odds(x.offer.price)}`,x.response.evaluation.recommended_units,x.response.recommended_dollars,{kind:'EXACT_OFFER',origin:'DETAIL',offer:x.offer,productVersion:x.response.product_version})}
async function submitWager(e){e.preventDefault();const p=state.pending,u=$('wager-units').value===''?null:Number($('wager-units').value),d=$('wager-dollars').value===''?null:$('wager-dollars').value,n=$('wager-note').value;const body=p.kind==='HEADLINE'?buildHeadlineWagerPayload({productVersion:p.productVersion,headline:p.headline,actualUnits:u,actualDollars:d,note:n,idempotencyKey:p.idempotencyKey}):buildExactWagerPayload({productVersion:p.productVersion,offer:p.offer,actualUnits:u,actualDollars:d,note:n,idempotencyKey:p.idempotencyKey});try{const created=await api.createWager(body);$('wager-dialog').close();state.pending=null;await refreshProduct();await loadWagers();if(p.kind==='EXACT_OFFER'){if(p.origin==='DETAIL'&&state.detailOffer){state.detailOffer.logged=created?.wager||findExactWager(state.detailOffer.offer);renderDetailOfferResult()}else if(state.exact){state.exact.logged=created?.wager||findExactWager(state.exact.offer);renderExactResult()}}toast('Wager logged.')}catch(err){$('wager-error').textContent=safe(err,'wager');if(err instanceof ApiError&&err.status===409)await refreshProduct()}}
async function loadWagers(){if(!auth()){state.wagers=[];renderWagers();return}try{state.wagers=(await api.wagers()).wagers||[]}catch(e){if(e instanceof ApiError&&e.status===401){state.user=state.profile=null;state.wagers=[]}}renderWagers()}
function filteredWagers(){const f=$('wager-filter')?.value||'';if(!f)return state.wagers;if(f==='open')return state.wagers.filter(w=>w.status==='OPEN');return state.wagers.filter(w=>SETTLED.has(w.status))}
function renderWagers(){const h=$('wager-list');if(!auth()){h.innerHTML='<div class="empty-state"><strong>Sign in to see saved wagers</strong></div>';return}const wagers=filteredWagers();if(!wagers.length){h.innerHTML='<div class="empty-state">No saved wagers in this view.</div>';return}h.innerHTML=`<div class="wager-cards">${wagers.map(w=>`<article class="wager-card"><div class="wager-top"><span class="state-chip">${esc(w.status)}</span><span>${esc(w.created_at)}</span></div><h3>${esc(w.game_id)}</h3><p>${esc(w.market_type)} · ${esc(w.selection)} ${line(w.line)} · ${w.book==='MANUAL'?'Manual entry':esc(bookName(w.book))} ${odds(w.price)}</p><div class="wager-money"><span>Actual <strong>${money(w.actual_dollars)}</strong></span><span>Recommended <strong>${money(w.recommended_dollars)}</strong></span></div><label class="status-control">Status <select data-status="${esc(w.wager_id)}">${WAGER_STATUSES.map(s=>`<option ${s===w.status?'selected':''}>${s}</option>`).join('')}</select></label></article>`).join('')}</div>`;h.querySelectorAll('[data-status]').forEach(s=>s.onchange=async()=>{try{await api.patchWager(s.dataset.status,{status:s.value});await loadWagers();await refreshProduct();toast('Wager status updated.')}catch(e){toast(safe(e))}})}
function renderAccount(){const h=$('account-content'),iosInstall=/iPhone|iPad|iPod/.test(navigator.userAgent)?'<section class="install-help">Safari → Share → Add to Home Screen</section>':'';if(!state.user){h.innerHTML=`<section class="auth-grid"><form id="login-form" class="setup-card auth-card"><h2>Sign in</h2><div class="manual-field"><label for="login-user">Username</label><input id="login-user" autocomplete="username" required></div><div class="manual-field"><label for="login-pass">Password</label><input id="login-pass" type="password" autocomplete="current-password" required></div><div id="login-error" class="form-error" role="alert"></div><button class="btn-primary full-btn" type="submit">Sign in</button></form><form id="register-form" class="setup-card auth-card"><h2>Create account</h2><div class="manual-field"><label for="reg-user">Username</label><input id="reg-user" required></div><div class="manual-field"><label for="reg-pass">Password</label><input id="reg-pass" type="password" minlength="10" required></div><div class="manual-field"><label for="reg-confirm">Confirm password</label><input id="reg-confirm" type="password" minlength="10" required></div><div id="reg-error" class="form-error" role="alert"></div><button class="btn-primary full-btn" type="submit">Create account</button></form></section>${iosInstall}`;$('login-form').onsubmit=login;$('register-form').onsubmit=register;return}const p=state.profile||state.user;h.innerHTML=`<section class="bank-hero"><div class="bank-label">Signed in as</div><div class="account-name">${esc(p.username)}</div><p class="section-sub">Your bankroll and risk profile personalize wager sizing.</p></section><form id="profile-form" class="week-card"><h2>Bankroll & risk</h2><div class="manual-field"><label for="bankroll">Bankroll</label><input id="bankroll" type="number" min="0" step="0.01" value="${esc(p.bankroll)}" required></div><div class="manual-field"><label for="risk">Risk profile</label><select id="risk">${RISK_PROFILES.map(r=>`<option ${r===p.risk_profile?'selected':''}>${r}</option>`).join('')}</select></div><div id="profile-error" class="form-error" role="alert"></div><button class="btn-primary" type="submit">Save settings</button></form><div class="account-actions"><button id="logout-btn" class="btn-secondary" type="button">Log out</button></div>${iosInstall}`;$('profile-form').onsubmit=updateProfile;$('logout-btn').onclick=logout}
async function login(e){e.preventDefault();try{await api.login($('login-user').value,$('login-pass').value);await refreshAuth();show('board');toast('Signed in.')}catch(x){$('login-error').textContent=safe(x,'login')}}
async function register(e){e.preventDefault();if($('reg-pass').value!==$('reg-confirm').value){$('reg-error').textContent='Passwords do not match.';return}try{await api.register($('reg-user').value,$('reg-pass').value);await refreshAuth();show(Number(state.profile?.bankroll)===0?'account':'board');toast('Account created.')}catch(x){$('reg-error').textContent=safe(x)}}
async function updateProfile(e){e.preventDefault();try{state.profile=await api.updateProfile({bankroll:$('bankroll').value,risk_profile:$('risk').value});state.user=state.profile;await refreshProduct();renderAll();toast('Profile updated. Dollar recommendations refreshed.')}catch(x){$('profile-error').textContent=safe(x)}}
async function logout(){try{await api.logout()}catch(e){if(!(e instanceof ApiError&&e.status===401)){toast(safe(e));return}}state.user=state.profile=null;state.wagers=[];state.exact=null;state.detailOffer=null;await refreshProduct();renderAll();show('board');toast('Logged out.')}
async function refreshProduct(){try{const v=await api.productLatest();state.view=v;if(v.user){state.user=v.user;state.profile=v.user}else{state.user=state.profile=null;state.wagers=[]}state.refreshError=null}catch(e){state.refreshError=safe(e)}renderHealth();renderUser();renderBoard()}
async function refreshAuth(){const me=await api.me();state.user=me.user;state.profile=await api.profile();await refreshProduct();await loadWagers();renderAll()}
async function refreshAll(){state.refreshError=null;await Promise.all([api.health().then(x=>state.health=x).catch(e=>{state.health=null;state.refreshError=safe(e)}),api.games().then(x=>state.games=x.games||[]).catch(e=>state.refreshError=safe(e)),api.me().then(x=>state.user=state.profile=x.user).catch(e=>{if(e instanceof ApiError&&e.status===401)state.user=state.profile=null}),api.productLatest().then(x=>state.view=x).catch(e=>state.refreshError=safe(e))]);if(state.user)try{state.profile=await api.profile()}catch{}renderAll();await loadWagers();if(state.exact){state.exact.logged=findExactWager(state.exact.offer);renderExactResult()}if(state.detailOffer){state.detailOffer.logged=findExactWager(state.detailOffer.offer);renderDetailOfferResult()}}
function renderAll(){renderHealth();renderUser();renderBoard();renderGames();populateExact();renderWagers();renderAccount()}
function show(name){['board','detail','check','bets','account'].forEach(v=>{const n=$(`view-${v}`);if(n)n.hidden=v!==name});document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('is-active',b.dataset.nav===name));$('back-btn').hidden=name!=='detail';if(name==='bets')loadWagers();if(name==='account')renderAccount();window.scrollTo({top:0,behavior:'auto'})}
function install(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.install=e;$('install-btn').hidden=false});$('install-btn').onclick=async()=>{if(!state.install)return;await state.install.prompt();state.install=null;$('install-btn').hidden=true};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{})}
$('refresh-btn').onclick=refreshAll;$('back-btn').onclick=()=>show('board');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));$('offer-game').onchange=exactSelections;$('offer-market').onchange=exactSelections;$('exact-form').onsubmit=evaluateExact;$('wager-form').onsubmit=submitWager;$('wager-dialog-close').onclick=()=>$('wager-dialog').close();$('wager-cancel').onclick=()=>$('wager-dialog').close();$('wager-filter').onchange=renderWagers;window.addEventListener('online',refreshAll);window.addEventListener('offline',renderHealth);install();refreshAll();
