export const RISK_PROFILES=['Cautious','Conservative','Normal','Aggressive','Ultra'];
export const WAGER_STATUSES=['OPEN','WON','LOST','PUSH','VOID','CANCELLED'];
export const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
export const odds=v=>v==null?'—':`${Number(v)>0?'+':''}${Number(v)}`; export const line=v=>v==null?'':`${Number(v)>0?'+':''}${Number(v)}`; export const money=v=>v==null?'—':`$${Number(v).toFixed(2)}`; export const pct=v=>v==null?'—':`${(Number(v)*100).toFixed(1)}%`; export const units=v=>v==null?'—':`${Number(v)}u`;
export function healthPresentation(h){ if(!h||h.api_healthy===false||h.database_healthy===false||!h.product_available)return{key:'unavailable',label:'Temporarily unavailable'}; const f=String(h.product_freshness||'UNAVAILABLE').toUpperCase(); if(h.product_stale||f==='STALE')return{key:'stale',label:'Data stale'}; if(f==='AGING')return{key:'aging',label:'Data aging'}; if(f==='UNAVAILABLE')return{key:'unavailable',label:'Temporarily unavailable'}; if(h.last_refresh_failed)return{key:'last-good',label:'Updated recently — last refresh failed'}; return{key:'fresh',label:'Updated recently'}; }
export function playThroughPresentation(currentLine,currentOdds,t){ if(!t||t.price_american==null)return null; const tm=t.line==null, cm=currentLine==null; const same=(tm&&cm)||(!tm&&!cm&&Number(t.line)===Number(currentLine)); return{...t,inside:same&&Number.isFinite(Number(currentOdds))?Number(currentOdds)>=Number(t.price_american):null}; }
export function roofPresentation(g){ const x=g?.football_outputs?.xgboost_v2||{}; if(!x.roof_resolution_status)return{kind:'ordinary',label:null}; if(['OPEN','CLOSED'].includes(x.roof_resolution_status))return{kind:'resolved',label:`Roof ${x.roof_resolution_status}`,detail:'Model-selected roof scenario.'}; const d=x.roof_scenario_downstream||{}; if(d.agreement_status==='ROOF_SENSITIVE'||d.status==='ROOF_SENSITIVE')return{kind:'sensitive',label:'ROOF SENSITIVE',detail:'Open and closed scenarios differ and are not averaged.'}; if(d.agreement_status==='AGREE')return{kind:'agree',label:'Roof scenarios agree',detail:'Open and closed scenarios share the same downstream state.'}; return{kind:'missing',label:'Roof evidence incomplete',detail:'No shared roof state is available.'}; }
export function headlinePresentation(h,o={},auth=false){ const state=String(h?.state||'UNSUPPORTED'); const duplicate=o.stake_suppressed_reason==='DUPLICATE_EXACT_OFFER'; const cancelled=String(o.wager_status||'').toUpperCase()==='CANCELLED'; const logged=!!o.wager_logged&&!cancelled; return{state,duplicate,logged,actionable:state==='BET'&&!duplicate&&!logged,recommendedDollars:auth&&!duplicate?(o.recommended_dollars??null):null,showSignIn:!auth&&state==='BET'}; }
export const buildHeadlineWagerPayload=({productVersion,headline,actualUnits,actualDollars,note,idempotencyKey})=>({source_type:'HEADLINE',product_version:productVersion,lane:headline.lane,actual_units:actualUnits,actual_dollars:actualDollars,note:note||null,idempotency_key:idempotencyKey});
export const buildExactWagerPayload=({productVersion,offer,actualUnits,actualDollars,note,idempotencyKey})=>({source_type:'EXACT_OFFER',product_version:productVersion,exact_offer:offer,actual_units:actualUnits,actual_dollars:actualDollars,note:note||null,idempotency_key:idempotencyKey});
