"""QB-Elo, opponent-adjusted margin, XGBoost, and stacker implementations."""

from .qb_elo import (
    EloConfig,
    EloState,
    PregamePrediction,
    QBAdjustmentConfig,
    TeamState,
    UpdateRecord,
    apply_season_carryover,
    clamp_probability,
    config_from_dict,
    config_to_dict,
    elo_expected,
    elo_probability_home,
    ensure_team,
    initial_state,
    mov_multiplier,
    predict_game,
    qb_adjustment_for,
    rebuild_state_from_ledger,
    update_state_with_margin,
)

__all__ = [
    "EloConfig",
    "EloState",
    "QBAdjustmentConfig",
    "PregamePrediction",
    "TeamState",
    "UpdateRecord",
    "apply_season_carryover",
    "clamp_probability",
    "config_from_dict",
    "config_to_dict",
    "ensure_team",
    "elo_expected",
    "elo_probability_home",
    "initial_state",
    "mov_multiplier",
    "predict_game",
    "qb_adjustment_for",
    "rebuild_state_from_ledger",
    "update_state_with_margin",
]